#!/bin/sh

. /etc/rc.subr

name="ftp_watchd"
rcvar="ftp_watchd_enable" # The variable in rc.conf that will allow this service to run
load_rc_config "ftp_watchd" # Loads the config file, if relevant.

pidfile="/var/run/pure-uploadscript.pid"
command="/usr/local/sbin/pure-uploadscript"
command_args="-B -r $ftp_watched_command -p $pidfile"

fstop() {
    pid=$(check_pidfile $pidfile /usr/local/sbin/pure-uploadscript)
    if [ -z "$pid" ]; then #ftp-watchd is not running
        echo "$name is not running."
    else
    echo Kill: $pid
    kill -9 $pid
    fi
}

stop_cmd="fstop"
run_rc_command "$1"
